apiVersion: v1
kind: Pod
metadata:
  name: tf-demo20
  namespace: tf-malleable-example
spec:
  containers:
  - name: tf-demo-ctr20
    image: tf-kubernetes
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-ce", "/data/launch_all.sh" ]
    volumeMounts:
    - mountPath: /data
      name: volume
  volumes:
  - name: volume
    hostPath: 
      path: /data
